# Generated by Django 3.2.5 on 2021-07-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='photos',
            field=models.ManyToManyField(related_name='albums', to='photo_share.Photo'),
        ),
    ]
